name: .NET

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  build-domain:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'src/Foundation.Domain/') || contains(github.event.head_commit.modified, 'tests/Adasit.Foundation.DomainTests/')
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Install SonarCloud scanner
      run: dotnet tool install --global dotnet-sonarscanner
    
    - name: Install coverage tools
      run: dotnet tool install --global dotnet-coverage
    
    - name: Restore dependencies
      run: dotnet restore src/Foundation.Domain/Adasit.Foundation.Domain.csproj
    
    - name: Begin SonarCloud analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        dotnet-sonarscanner begin \
          /k:"adas-it_foundation" \
          /o:"adas-it" \
          /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
          /d:sonar.host.url="https://sonarcloud.io" \
          /d:sonar.cs.vscoveragexml.reportsPaths=coverage-domain.xml
    
    - name: Build
      run: dotnet build src/Foundation.Domain/Adasit.Foundation.Domain.csproj --no-restore --configuration Release
    
    - name: Test with coverage
      run: dotnet-coverage collect 'dotnet test tests/Adasit.Foundation.DomainTests/Adasit.Foundation.DomainTests.csproj --no-build --configuration Release --verbosity normal' -f xml -o 'coverage-domain.xml'
    
    - name: End SonarCloud analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
    
    - name: Pack NuGet package
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
      run: dotnet pack src/Foundation.Domain/Adasit.Foundation.Domain.csproj --configuration Release --no-build --output ./artifacts
    
    - name: Display package version
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
      run: |
        echo "Package version:"
        ls -la ./artifacts/*.nupkg
    
    - name: Publish to GitHub Packages
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
      run: dotnet nuget push ./artifacts/*.nupkg --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.ARTIFACTORY_TOKEN }} --skip-duplicate

  build-dto:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'src/Foundation.Dto/') || contains(github.event.head_commit.modified, 'tests/Adasit.Foundation.DtoTests/')
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Install SonarCloud scanner
      run: dotnet tool install --global dotnet-sonarscanner
    
    - name: Install coverage tools
      run: dotnet tool install --global dotnet-coverage
    
    - name: Restore dependencies
      run: dotnet restore src/Foundation.Dto/Adasit.Foundation.Dto.csproj
    
    - name: Begin SonarCloud analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        dotnet-sonarscanner begin \
          /k:"adas-it_foundation-dto" \
          /o:"adas-it" \
          /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
          /d:sonar.host.url="https://sonarcloud.io" \
          /d:sonar.cs.vscoveragexml.reportsPaths=coverage-domain.xml
    
    - name: Build
      run: dotnet build src/Foundation.Dto/Adasit.Foundation.Dto.csproj --no-restore --configuration Release
    
    - name: Test with coverage
      run: dotnet-coverage collect 'dotnet test tests/Adasit.Foundation.DtoTests/Adasit.Foundation.DtoTests.csproj --no-build --configuration Release --verbosity normal' -f xml -o 'coverage-domain.xml'
    
    - name: End SonarCloud analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
    
    - name: Pack NuGet package
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
      run: dotnet pack src/Foundation.Domain/Adasit.Foundation.Dto.csproj --configuration Release --no-build --output ./artifacts
    
    - name: Display package version
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
      run: |
        echo "Package version:"
        ls -la ./artifacts/*.nupkg
    
    - name: Publish to GitHub Packages
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
      run: dotnet nuget push ./artifacts/*.nupkg --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.ARTIFACTORY_TOKEN }} --skip-duplicate
